### ISSUE TITLE
Launch file argument

### ISSUE THREAD

**Issue by maffan-96** [OPT4SMART/ChoiRbot#4]
When i tried launching the containment simulation via "ros2 launch choirbot_examples containment.launch.py -n 6," it returns a following error with ROS foxy.

usage: ros2 [-h] Call `ros2 <command> -h` for more detailed usage. ...
ros2: error: unrecognized arguments: 6

**Comment by andrea-testa** [comment]
Hi, thank you for your inquiry. Foxy has changed the way in which launch files can receive arguments from terminal. We are investigating how to fix this. In the meanwhile, you can run 'ros2 launch choirbot_examples containment.launch.py' and set by hand in the containment.launch.py files how many robots you want to simulate. Specifically, instead of N = args.number, just write N=6. After modifying the launch file, remember to launch 'colcon build' again :)

**Comment by andrea-testa** [comment]
Hi, I just updated how the launch files process command line arguments. Instead on "-n 6", it is now possible to use "N:=6".
I will update the documentation accordingly.
